### PR TITLE
Add post install script

### PR DESCRIPTION
**Pull request by therealklanni**
Does not break Docker. (#126) 

Trying this again, since maintainer closed without comment.

### CODE REVIEW

**Comment by justinleewells** [comment]
I've actually never heard of SKIP_POSTINSTALL before. This looks fine though.

**Comment by mathiasbynens** [comment]
> I've actually never heard of `SKIP_POSTINSTALL` before.

FYI: it’s nothing standard, it’s just an arbitrarily chosen Bash variable name — it could’ve been `YOLO_SWAGGERBOIII` or anything else ;)

The [custom npm `postinstall` script](https://github.com/justinleewells/pogo-optimizer/pull/149/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R25) checks if `SKIP_POSTINSTALL` has a value and doesn’t do anything in that case.

**Comment by justinleewells** [comment]
I appreciate the explanation. I couldn't find much when googling it, which makes sense if it's apparently non-standard.

**Comment by therealklanni** [comment]
@mathiasbynens I definitely should have gone with `YOLO_SWAGGERBOIII`, dunno why I didn't think of that. ;)

**Pull request merged**
